#!/usr/bin/expect -f

set timeout 5
set port $::env(SDTD_TELNET_PORT)
set password $::env(SDTD_TELNET_PASSWORD)

spawn telnet localhost $port

expect "Please enter password:"
log_user 0
send "$password\r"
expect "\r"
log_user 1
puts "\n********"
expect "Logon successful"

send "saveworld\r"
expect {
  "World saved" {}
  "Command 'saveworld' can only be executed when a game is started" {}
}

send "shutdown\r"
send "exit\r"
expect eof
