#!/usr/bin/expect -f

set timeout 5
set port $::env(SDTD_TELNET_PORT)
set password $::env(SDTD_TELNET_PASSWORD)

spawn telnet localhost $port

log_user 0
expect "Please enter password:"
send "$password\n"
expect "Logon successful"
log_user 1

send "saveworld\n"
expect {
  "World saved" {}
  "Command 'saveworld' can only be executed when a game is started" {}
}

send "shutdown\n"
send "exit\n"
expect eof
