#!/usr/bin/env bash

set -euo pipefail

args=

if [[ "${DOCKER_TAG}" != latest ]]; then
  args=(--build-arg VERSION="${DOCKER_TAG}")
fi

docker build ${args[@]} -f "${DOCKERFILE_PATH}" -t "${IMAGE_NAME}" .
